[package]
name = "ffmpegtrim"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.12", features = ["derive"] }
ffmpeg-sidecar = "0.4.1"
pbr = "1.0.4"
